### ISSUE TITLE
Field Titles in Modals have a strikethrough (Only in the deployed version of the app)

### ISSUE THREAD

**Issue by Infinity-Intellect** [curefit/react-crux#119]
When  I deploy my code, there's a strike-through appearing on all of the field titles in the modals. I suspect there's some issue with `react-tooltip` because deleting that particular element using the developer console removes the strike-through.

![strikethroughIssue](https://user-images.githubusercontent.com/49329642/102504190-87addf80-40a6-11eb-956c-0fb14ddf73e5.PNG)

**Comment by ankitcf** [comment]
Can you help us reproduce ? The examples on https://curefit.github.io/react-crux-examples/#/ dont seem to have the issue

**Comment by Infinity-Intellect** [comment]
What I did was
1. Pulled the example from https://github.com/curefit/react-crux-examples
2. Added some of my own entities.
3. Finally, deployed the application.

Weirdly enough, during development  I did not encounter the strike-through, but when I deployed the application, it shows up.
What I'm wondering is whether the examples at https://curefit.github.io/react-crux-examples/ is using an older version. Because I don't see the react-tooltip div element in the inspect element at https://curefit.github.io/react-crux-examples.

The https://curefit.github.io/react-crux-examples inspect element of the title field 'NAME',

![deployedcrux](https://user-images.githubusercontent.com/49329642/102585950-4877a100-412f-11eb-95a4-e79f3e5bba33.PNG)

My deployed application's inspect element of the title field 'NAME',

![deployedMyCrux](https://user-images.githubusercontent.com/49329642/102585986-5a594400-412f-11eb-80d0-7d2cea448603.PNG)

**Comment by ankitcf** [comment]
Can you compare you yarn.lock file with the one in the project and see which version for which package is different.

Also do you have deployed version hosted somewhere we can look ?

**Comment by Infinity-Intellect** [comment]
The example at https://github.com/curefit/react-crux-examples seems to be using an older crux version `"react-crux": "^0.0.39"`.
I'm using `"react-crux": "^0.20.2"`.

**Comment by ankitcf** [comment]
Ok. Give us some time to reproduce this and fix it. Alternately if you know the fix, we would be happy to review a PR

**Comment by kunal15595** [comment]
Fix in #120
